/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examsoftgui;

import java.io.File;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JToggleButton;

/**
 *
 * @author zubaeyr
 */
public class WarningPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarningPanel
     */
     int unattempted,noofque;
    String[] answers;
    int[] quetype;
    JPanel frame;
    String ID;
    String Subject;
    String Ip;
    JPanel panel1,panel2;
    JToggleButton buttona,buttonb;
    JButton buttonc;
    JScrollPane scpane;
    int first=0;
    
    public WarningPanel(int unattempted,int noofque, int quetype[], String answers[],String ID, String Subject,String Ip,JToggleButton button1,JToggleButton button2, JButton button3,JPanel panel1,JPanel panel2){
        this.Subject=Subject;
        this.answers=answers;
        this.quetype=quetype;
        this.noofque=noofque;
        this.ID=ID;
        button1.setEnabled(false);
            button2.setEnabled(false);
            button3.setEnabled(false);
        first=0;
        this.Ip=Ip;
        this.buttona=button1;
        this.buttonb=button2;
        this.buttonc=button3;
         
        this.panel1=panel1;
        this.panel2=panel2;
        this.unattempted=unattempted;

        initComponents();        
        this.show(true);
        this.revalidate();
    }

     public WarningPanel(int unattempted,int noofque, int quetype[], String answers[],String ID, String Subject,String Ip,JToggleButton button1,JToggleButton button2, JButton button3,JPanel panel1,JScrollPane scpane){
        this.Subject=Subject;
        this.answers=answers;
        this.quetype=quetype;
        this.noofque=noofque;
        this.ID=ID;
        button1.setEnabled(false);
            button2.setEnabled(false);
            button3.setEnabled(false);
        first=1;
        this.Ip=Ip;
        this.buttona=button1;
        this.buttonb=button2;
        this.buttonc=button3;
         
        this.panel1=panel1;
        this.scpane=scpane;
        this.unattempted=unattempted;

        initComponents();

        this.show(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Oops! Looks like You've not attempted "+unattempted+" Questions yet!");
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));// NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Do ye still wanna Submit?");

        jButton1.setText("Hell, yeah!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nope!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Call the output function
        this.buttona.setEnabled(true);
        this.buttonb.setEnabled(true);
        this.buttonc.setEnabled(true);
        this.setVisible(false);
        this.show(false);
        this.hide();
        panel1.show(true);
        panel1.revalidate();
        if(first==0){
            panel2.show(true);
            panel2.revalidate();
        }else if(first==1){
            scpane.show(true);
            scpane.revalidate();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<quetype.length;i++){
            
            if(quetype[i]!=2 && answers[i]=="N"){
                answers[i]="U";
            }
            try {
      String path=this.getClass().getResource("/examsoftgui/").getPath().toString().trim();
      int counter=0;
      int start=0,end=0;
      for(end=0;end<path.length();end++){
          if(path.charAt(end)=='/'&& counter!=3){
              counter++;
              if(counter==1){
                    start=end;
                }
          }
          if(counter==3){
              break;
          }
         
      }
      path=path.substring(start,end+1);  
      File f=new File(path+".gnome2/eog/catch/");
      String[] files=f.list();
      for(int h=0;h<files.length;h++){
        
          File file=new File(path+".gnome2/eog/catch/"+files[h]);
          file.delete();
      }
      
 
                SendAnswers sender=new SendAnswers(Ip,ID,Subject,answers);
            } catch (IOException ex) {
                //CAnnot SEnd Error
            }
        }
            new AnswerFileGenerator(answers,ID,Subject);

     
            System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
